### ISSUE TITLE
Released version with dist-tag latest on NPM doesn't seem to be working

### ISSUE THREAD

**Issue by parangsjo-ingka** [fastly/compute-js-opentelemetry#74]
The released version having dist-tag `latest` (`0.1.0`) on NPM (www.npmjs.com) doesn't seem to be working. Could you please update the `latest` dist-tag on NPM to a working version? It seems like `0.1.3` is not working at the time either, so we're currently relying on the latest alpha version (`0.2.0-alpha.3`).

Great work on this implementation!

**Comment by harmony7** [comment]
Thanks for reaching out.

0.2.0 branch appears to be testing well, so we will likely release it as `latest` soon. Please use `alpha` for now, and thanks for your patience.

**Comment by harmony7** [comment]
We just released `0.2.0` as `latest`. Please check it out!

**Comment by parangsjo-ingka** [comment]
@harmony7 Many thanks for the quick action to our original request! Btw, we tend to use TypeScript for our C@E services, do you have plans for adding examples with recommendations for how compute-js-opentelemetry lib should be used then? Please let me  know.
