### ISSUE TITLE
Example when C@E service is written in TypeScript

### ISSUE THREAD

**Issue by parangsjo-ingka** [fastly/compute-js-opentelemetry#76]
Can you please provide an example of how the OpenTelemetry implementation is properly setup and configured when the Compute@Edge service is written in TypeScript? Thank you.

**Comment by harmony7** [comment]
Please take a look:
https://github.com/fastly/compute-js-opentelemetry/tree/main#use-with-typescript

There are also two new samples in the examples directory.

Note you'll need 0.2.1 or newer as this fixes a bug with loaders.
